// <auto-generated />
namespace TheBookingPlatform.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class emailtemplate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(emailtemplate));
        
        string IMigrationMetadata.Id
        {
            get { return "202310141231553_emailtemplate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
