// <auto-generated />
namespace TheBookingPlatform.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class userisactive : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userisactive));
        
        string IMigrationMetadata.Id
        {
            get { return "202401071821553_userisactive"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
