// <auto-generated />
namespace TheBookingPlatform.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class lastsetupforgoogle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lastsetupforgoogle));
        
        string IMigrationMetadata.Id
        {
            get { return "202409171131383_lastsetupforgoogle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
